# Generated by Django 5.1.4 on 2025-02-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_oraganizations_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
