# Generated by Django 5.1.4 on 2025-02-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizations_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compititions',
            name='time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='time',
            field=models.TextField(),
        ),
    ]
